detail:
  - name: small
    width: 100
    height: 100
    hint: Картинка для главной страницы
    mustcrop: yes

  - name: preview
    width: 400
    height: 100

product:
  - name: big
    width: 1000
    height: 2000
    hint: Картинка под лупой
    mustcrop: yes

  - name: preview
    width: 300
    height: 80
    hint: Картинка на странице продукта
    mustcrop: yes

mainpage:
  - name: default
    width: 100
    height: 80
    mustcrop: yes